name: Build Docker image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:

  build:

    runs-on: ubuntu-latest
    env:
      IMAGE: ghcr.io/kcdubois/eris
      TAG: github.sha
      
    steps:
    - uses: actions/checkout@v4
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag $IMAGE:$TAG
      
    - name: Download Wiz CLI
      run: curl -o wizcli https://downloads.wiz.io/wizcli/latest/wizcli-linux-amd64 && chmod +x wizcli

    - name: Authenticate to Wiz
      run: ./wizcli auth --id "$WIZ_CLIENT_ID" --secret "$WIZ_CLIENT_SECRET"
      env:
        WIZ_CLIENT_ID: ${{ secrets.WIZ_CLIENT_ID }}
        WIZ_CLIENT_SECRET: ${{ secrets.WIZ_CLIENT_SECRET }}

    - name: Run Wiz docker image scan
      run: ./wizcli docker scan --image $IMAGE:$TAG --policy "$POLICY"

  push:
     runs-on: ubuntu-latest
     steps:
      - uses: actions/checkout@v4
      - name: Fetch digest of Docker image for Graph enrichment
        run: ./wizcli docker tag --image $IMAGE:$TAG
